### ISSUE TITLE
X and Y flip on multi-tile stamps

### ISSUE THREAD

**Issue by to-be-determined-or-not** [LittleB0xes/LDtkBridge#1]
I'm just starting out with both LDtk and DragonRuby, so this bridge came in handy. I have a LDtk level with 16x16 tiles, some tiles form a bigger tile e.g. 32x32 -- 4 tiles in a 2x2 stamp. I got the bridge to work with my sample level, and found a few stamps were showing up wrong due to being x and/or y flipped:

![image](https://user-images.githubusercontent.com/83912511/156867545-b061a350-beb5-4309-9eab-14a4b5a48577.png)

I don't quite know what to do with the info yet, but the tile's "f" field tracks the flip with 0=none, 1=x , 2=y, 3=both).

**Comment by LittleB0xes** [comment]
Thanks for using my bridge.
In LDtk, do you use different grid sizes on the layers?
Indeed, the support of the possibilities of LDtk is only partial on LDtkBridge. I only added what I used. I never used different grid size in same LDtk project...
~~So currently, LDtk doesn't support multiple grid size, but I can dive back into the code and into the json of LDtk to try and add it.~~


In the meantime, a very practical option of LDtk is the export of each layer of each level as an independent png file that you can then use directly as a classic image in DragonRuby (big performance gain because you display a single image per layer instead... many)

**Comment by LittleB0xes** [comment]
Oops, I misunderstand your issue...
I'll take a look at the rotations

**Comment by LittleB0xes** [comment]
Which version of LDtk are you using ?

**Comment by LittleB0xes** [comment]
I just added the flip field `f` in `layer_data`
normally you should now have access to this value by `you_layer.layer_data[tile_index][:f]`
(with same value as LDtk :  0, 1, 2 or 3)
Could you do a test?

**Comment by LittleB0xes** [comment]
Now, works here
<img width="314" alt="Capture d’écran 2022-03-05 à 11 25 52" src="https://user-images.githubusercontent.com/458285/156879297-1a8991f6-cc9e-4b14-b992-ca87f2d544bf.png">
 
 We can also discuss about a more DragonRuby friendly notation ;-)

**Comment by LittleB0xes** [comment]
If you want, I can add the `flip_vertically` and the `flip_horizontally` fields with boolean value in each data tile to be DR friendly ?

**Comment by to-be-determined-or-not** [comment]
I downloaded the newer version, added the flip assignments to my code, and all looks good. Thanks for the quick reply!

![image](https://user-images.githubusercontent.com/83912511/156890498-a7b34930-97d9-4be6-8bc5-b1ba3ee79ca8.png)
